version: '3.7'

services:

  db:
    image: postgres:10.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/10

  chefbot:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - db

volumes:
  db-data: