version: '3.7'

services:

  db:
    image: postgres:10.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

  chefbot:
    image: xiaoxiao921/chef:latest
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      GOOGLE_APPLICATION_CREDENTIALS: /does/not/matter.json
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./ChefBot-ocr.json:/does/not/matter.json
    depends_on:
      - db

volumes:
  db-data:
