name: Docker Image Debug
on:
  repository_dispatch:
    types: docker-debug
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Dotnet Setup
      uses: actions/setup-dotnet@v1
    - name: Build with dotnet
      run: dotnet build --configuration Debug
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish CHEF.sln --configuration Debug --framework netcoreapp2.1 --output ./publish --self-contained false
    - name: Login to DockerHub Registry
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the tagged Docker image
      run: docker build . --file Docker/Dockerfile --tag xiaoxiao921/chef:debug
    - name: Push the tagged Docker image
      run: docker push xiaoxiao921/chef:debug
