name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Dotnet Setup
      uses: actions/setup-dotnet@v1.5.0
      with:
        dotnet-version: 2.1.514
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish CHEF.sln --configuration Release --framework netcoreapp2.1 --output ./publish --self-contained false
    - name: Login to DockerHub Registry
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build the tagged Docker image
      run: docker build . --file Docker/Dockerfile --tag xiaoxiao921/chef:${{steps.vars.outputs.tag}}
    - name: Push the tagged Docker image
      run: docker push xiaoxiao921/chef:${{steps.vars.outputs.tag}}
    - name: Build the latest Docker image
      run: docker build . --file Docker/Dockerfile --tag xiaoxiao921/chef:latest
    - name: Push the latest Docker image
      run: docker push xiaoxiao921/chef:latest
